version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      wow-build-tools:
        patterns:
          - McTalian/wow-build-tools*
          - McTalian-WoW-Addons/wow-build-tools*
