name: Package and release (CF)

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}

    steps:
      - name: Clone project
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Package and distribute
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        # trunk-ignore(pinact/unpinned-action)
        uses: McTalian-WoW-Addons/wow-build-tools@v1
        with:
          args: -t ./TokenTransmogTooltips -r ./.release
