name: Package and release (WAGO)

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Package and distribute
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        # trunk-ignore(pinact/unpinned-action)
        uses: McTalian-WoW-Addons/wow-build-tools@v1
        with:
          args: -t ./TokenTransmogTooltips -r ./.release
