name: Package and release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  package-and-release:
    permissions:
      contents: write
    uses: McTalian-WoW-Addons/wow-build-tools/.github/workflows/package-and-distribute.yml@v1-beta
    with:
      addon-name: TokenTransmogTooltips
      avatar-url: https://raw.githubusercontent.com/McTalian-WoW-Addons/TokenTransmogTooltips/refs/heads/main/logo.png
    secrets: inherit
