name: Package and release (WAGO)

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Package and distribute
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        # trunk-ignore(pinact/unpinned-action)
        uses: McTalian-WoW-Addons/wow-build-tools@v1
        with:
          args: -t ./TokenTransmogTooltips -r ./.release
